default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # url is optional, only used in production
  url: <%= ENV['DATABASE_URL'] %>

development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: db/development.sqlite3

test:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: db/test.sqlite3

production:
  <<: *default
  # Ensure you have DATABASE_URL set in Render
